[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
# (no keys needed here for now)

[dependencies.bootloader]
version = "0.9.23"
features = ["binary"]
